version: '3.1'
services:
  db:
    image: mysql:8.0.25
    container_name: socialapp-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: socialapp
      LANG: C.UTF-8
    ports:
      - "3307:3306"

  redis:
    image: 'redis:6-alpine'
    container_name: socialapp-redis
    ports:
      - "127.0.0.1:6382:6379"